config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :equipment

  resources :parts

  resources :work_orders

  resources :mileagelogs

  resources :timelogs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :work_order
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:part_number, :part_description, :unit_price, :unit_quantity, :parts_total, :work_order_id)
    end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= form_for @part, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :part_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :part_number, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :part_description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :part_description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :unit_price, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :unit_price, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :unit_quantity, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :unit_quantity, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :parts_total, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :parts_total, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  parts_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/parts/edit.html.erb
<%- model_class = Part -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Part %></h1>
</div>
<%= render :partial => 'form' %>

app/views/parts/index.html.erb
<%- model_class = Part -%>
<div class="page-header">
  <h1><%=t '.title', :default => Part %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:part_number) %></th>
      <th><%= model_class.human_attribute_name(:part_description) %></th>
      <th><%= model_class.human_attribute_name(:unit_price) %></th>
      <th><%= model_class.human_attribute_name(:unit_quantity) %></th>
      <th><%= model_class.human_attribute_name(:parts_total) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.id %></td>
        <td><%= part.part_number %></td>
        <td><%= part.part_description %></td>
        <td><%= part.unit_price %></td>
        <td><%= part.unit_quantity %></td>
        <td><%= part.parts_total %></td>
        <td><%=l part.created_at, format: :long %></td>
        <td>
          <%= link_to part_path(part), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to part_path(part), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_part_path,
            :class => 'btn btn-primary' %>

app/views/parts/new.html.erb
<%- model_class = Part -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Part %></h1>
</div>
<%= render :partial => 'form' %>

app/views/parts/show.html.erb
<%- model_class = Part -%>
<div class="page-header">
  <h1><%=t '.title', :default => Part %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:part_number) %></dt>
      <dd><pre class="prettyprint"><%= @part.part_number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:part_description) %></dt>
      <dd><pre class="prettyprint"><%= @part.part_description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:unit_price) %></dt>
      <dd><pre class="prettyprint"><%= @part.unit_price %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:unit_quantity) %></dt>
      <dd><pre class="prettyprint"><%= @part.unit_quantity %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:parts_total) %></dt>
      <dd><pre class="prettyprint"><%= @part.parts_total %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              parts_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_part_path(@part), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              part_path(@part),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>