config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :equipment

  resources :parts

  resources :work_orders

  resources :mileagelogs

  resources :timelogs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/timelog.rb
class Timelog < ActiveRecord::Base
  belongs_to :equipment
  belongs_to :work_order
end

app/controllers/timelogs_controller.rb
class TimelogsController < ApplicationController
  before_action :set_timelog, only: [:show, :edit, :update, :destroy]

  # GET /timelogs
  # GET /timelogs.json
  def index
    @timelogs = Timelog.all
  end

  # GET /timelogs/1
  # GET /timelogs/1.json
  def show
  end

  # GET /timelogs/new
  def new
    @timelog = Timelog.new
  end

  # GET /timelogs/1/edit
  def edit
  end

  # POST /timelogs
  # POST /timelogs.json
  def create
    @timelog = Timelog.new(timelog_params)

    respond_to do |format|
      if @timelog.save
        format.html { redirect_to @timelog, notice: 'Timelog was successfully created.' }
        format.json { render :show, status: :created, location: @timelog }
      else
        format.html { render :new }
        format.json { render json: @timelog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timelogs/1
  # PATCH/PUT /timelogs/1.json
  def update
    respond_to do |format|
      if @timelog.update(timelog_params)
        format.html { redirect_to @timelog, notice: 'Timelog was successfully updated.' }
        format.json { render :show, status: :ok, location: @timelog }
      else
        format.html { render :edit }
        format.json { render json: @timelog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timelogs/1
  # DELETE /timelogs/1.json
  def destroy
    @timelog.destroy
    respond_to do |format|
      format.html { redirect_to timelogs_url, notice: 'Timelog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timelog
      @timelog = Timelog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timelog_params
      params.require(:timelog).permit(:rate, :date, :nature_work, :hours_worked, :equipment_id, :total, :employee, :work_order_id)
    end
end

app/helpers/timelogs_helper.rb
module TimelogsHelper
end

app/views/timelogs/_form.html.erb
<%= form_for @timelog, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :rate, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :rate, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nature_work, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nature_work, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :hours_worked, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :hours_worked, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :total, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :total, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :employee, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :employee, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  timelogs_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/timelogs/edit.html.erb
<%- model_class = Timelog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Timelog %></h1>
</div>
<%= render :partial => 'form' %>

app/views/timelogs/index.html.erb
<%- model_class = Timelog -%>
<div class="page-header">
  <h1><%=t '.title', :default => Timelog %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:rate) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:nature_work) %></th>
      <th><%= model_class.human_attribute_name(:hours_worked) %></th>
      <th><%= model_class.human_attribute_name(:total) %></th>
      <th><%= model_class.human_attribute_name(:employee) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @timelogs.each do |timelog| %>
      <tr>
        <td><%= timelog.id %></td>
        <td><%= timelog.rate %></td>
        <td><%= timelog.date %></td>
        <td><%= timelog.nature_work %></td>
        <td><%= timelog.hours_worked %></td>
        <td><%= timelog.total %></td>
        <td><%= timelog.employee %></td>
        <td><%=l timelog.created_at, format: :long %></td>
        <td>
          <%= link_to timelog_path(timelog), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to timelog_path(timelog), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_timelog_path,
            :class => 'btn btn-primary' %>

app/views/timelogs/new.html.erb
<%- model_class = Timelog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Timelog %></h1>
</div>
<%= render :partial => 'form' %>

app/views/timelogs/show.html.erb
<%- model_class = Timelog -%>
<div class="page-header">
  <h1><%=t '.title', :default => Timelog %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:rate) %></dt>
      <dd><pre class="prettyprint"><%= @timelog.rate %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:date) %></dt>
      <dd><pre class="prettyprint"><%= @timelog.date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nature_work) %></dt>
      <dd><pre class="prettyprint"><%= @timelog.nature_work %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:hours_worked) %></dt>
      <dd><pre class="prettyprint"><%= @timelog.hours_worked %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:total) %></dt>
      <dd><pre class="prettyprint"><%= @timelog.total %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:employee) %></dt>
      <dd><pre class="prettyprint"><%= @timelog.employee %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              timelogs_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_timelog_path(@timelog), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              timelog_path(@timelog),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>