config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :equipment

  resources :parts

  resources :work_orders

  resources :mileagelogs

  resources :timelogs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/mileagelog.rb
class Mileagelog < ActiveRecord::Base
  belongs_to :work_order
end

app/controllers/mileagelogs_controller.rb
class MileagelogsController < ApplicationController
  before_action :set_mileagelog, only: [:show, :edit, :update, :destroy]

  # GET /mileagelogs
  # GET /mileagelogs.json
  def index
    @mileagelogs = Mileagelog.all
  end

  # GET /mileagelogs/1
  # GET /mileagelogs/1.json
  def show
  end

  # GET /mileagelogs/new
  def new
    @mileagelog = Mileagelog.new
  end

  # GET /mileagelogs/1/edit
  def edit
  end

  # POST /mileagelogs
  # POST /mileagelogs.json
  def create
    @mileagelog = Mileagelog.new(mileagelog_params)

    respond_to do |format|
      if @mileagelog.save
        format.html { redirect_to @mileagelog, notice: 'Mileagelog was successfully created.' }
        format.json { render :show, status: :created, location: @mileagelog }
      else
        format.html { render :new }
        format.json { render json: @mileagelog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mileagelogs/1
  # PATCH/PUT /mileagelogs/1.json
  def update
    respond_to do |format|
      if @mileagelog.update(mileagelog_params)
        format.html { redirect_to @mileagelog, notice: 'Mileagelog was successfully updated.' }
        format.json { render :show, status: :ok, location: @mileagelog }
      else
        format.html { render :edit }
        format.json { render json: @mileagelog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mileagelogs/1
  # DELETE /mileagelogs/1.json
  def destroy
    @mileagelog.destroy
    respond_to do |format|
      format.html { redirect_to mileagelogs_url, notice: 'Mileagelog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mileagelog
      @mileagelog = Mileagelog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mileagelog_params
      params.require(:mileagelog).permit(:starting_mile, :ending_mile, :rate, :total_miles, :mile_total_cost, :work_order_id)
    end
end

app/helpers/mileagelogs_helper.rb
module MileagelogsHelper
end

app/views/mileagelogs/_form.html.erb
<%= form_for @mileagelog, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :starting_mile, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :starting_mile, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ending_mile, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :ending_mile, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rate, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :rate, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :total_miles, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :total_miles, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mile_total_cost, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :mile_total_cost, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  mileagelogs_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/mileagelogs/edit.html.erb
<%- model_class = Mileagelog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Mileagelog %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mileagelogs/index.html.erb
<%- model_class = Mileagelog -%>
<div class="page-header">
  <h1><%=t '.title', :default => Mileagelog %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:starting_mile) %></th>
      <th><%= model_class.human_attribute_name(:ending_mile) %></th>
      <th><%= model_class.human_attribute_name(:rate) %></th>
      <th><%= model_class.human_attribute_name(:total_miles) %></th>
      <th><%= model_class.human_attribute_name(:mile_total_cost) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @mileagelogs.each do |mileagelog| %>
      <tr>
        <td><%= mileagelog.id %></td>
        <td><%= mileagelog.starting_mile %></td>
        <td><%= mileagelog.ending_mile %></td>
        <td><%= mileagelog.rate %></td>
        <td><%= mileagelog.total_miles %></td>
        <td><%= mileagelog.mile_total_cost %></td>
        <td><%=l mileagelog.created_at, format: :long %></td>
        <td>
          <%= link_to mileagelog_path(mileagelog), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to mileagelog_path(mileagelog), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_mileagelog_path,
            :class => 'btn btn-primary' %>

app/views/mileagelogs/new.html.erb
<%- model_class = Mileagelog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Mileagelog %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mileagelogs/show.html.erb
<%- model_class = Mileagelog -%>
<div class="page-header">
  <h1><%=t '.title', :default => Mileagelog %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:starting_mile) %></dt>
      <dd><pre class="prettyprint"><%= @mileagelog.starting_mile %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ending_mile) %></dt>
      <dd><pre class="prettyprint"><%= @mileagelog.ending_mile %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:rate) %></dt>
      <dd><pre class="prettyprint"><%= @mileagelog.rate %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:total_miles) %></dt>
      <dd><pre class="prettyprint"><%= @mileagelog.total_miles %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:mile_total_cost) %></dt>
      <dd><pre class="prettyprint"><%= @mileagelog.mile_total_cost %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              mileagelogs_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_mileagelog_path(@mileagelog), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              mileagelog_path(@mileagelog),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>