config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :equipment

  resources :parts

  resources :work_orders

  resources :mileagelogs

  resources :timelogs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  belongs_to :user
  has_many :parts
  has_many :mileagelogs
  has_many :timelogs
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: [:show, :edit, :update, :destroy]

  # GET /work_orders
  # GET /work_orders.json
  def index
    @work_orders = WorkOrder.all
  end

  # GET /work_orders/1
  # GET /work_orders/1.json
  def show
  end

  # GET /work_orders/new
  def new
    @work_order = WorkOrder.new
  end

  # GET /work_orders/1/edit
  def edit
  end

  # POST /work_orders
  # POST /work_orders.json
  def create
    @work_order = WorkOrder.new(work_order_params)

    respond_to do |format|
      if @work_order.save
        format.html { redirect_to @work_order, notice: 'Work order was successfully created.' }
        format.json { render :show, status: :created, location: @work_order }
      else
        format.html { render :new }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_orders/1
  # PATCH/PUT /work_orders/1.json
  def update
    respond_to do |format|
      if @work_order.update(work_order_params)
        format.html { redirect_to @work_order, notice: 'Work order was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_order }
      else
        format.html { render :edit }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_orders/1
  # DELETE /work_orders/1.json
  def destroy
    @work_order.destroy
    respond_to do |format|
      format.html { redirect_to work_orders_url, notice: 'Work order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_order
      @work_order = WorkOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_order_params
      params.require(:work_order).permit(:wo_number, :start_date, :comp_date, :requestor, :priority, :repair_facility, :repair_type, :location, :summary, :est_completion, :percent_complete, :user_id)
    end
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/work_orders/_form.html.erb
<%= form_for @work_order, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :wo_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :wo_number, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :start_date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :comp_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :comp_date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :requestor, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :requestor, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :priority, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :priority, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :repair_facility, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :repair_facility, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :repair_type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :repair_type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :location, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :summary, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :summary, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :est_completion, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :est_completion, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :percent_complete, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :percent_complete, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  work_orders_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/work_orders/edit.html.erb
<%- model_class = WorkOrder -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => WorkOrder %></h1>
</div>
<%= render :partial => 'form' %>

app/views/work_orders/index.html.erb
<%- model_class = WorkOrder -%>
<div class="page-header">
  <h1><%=t '.title', :default => WorkOrder %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:wo_number) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:comp_date) %></th>
      <th><%= model_class.human_attribute_name(:requestor) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:repair_facility) %></th>
      <th><%= model_class.human_attribute_name(:repair_type) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:summary) %></th>
      <th><%= model_class.human_attribute_name(:est_completion) %></th>
      <th><%= model_class.human_attribute_name(:percent_complete) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @work_orders.each do |work_order| %>
      <tr>
        <td><%= work_order.id %></td>
        <td><%= work_order.wo_number %></td>
        <td><%= work_order.start_date %></td>
        <td><%= work_order.comp_date %></td>
        <td><%= work_order.requestor %></td>
        <td><%= work_order.priority %></td>
        <td><%= work_order.repair_facility %></td>
        <td><%= work_order.repair_type %></td>
        <td><%= work_order.location %></td>
        <td><%= work_order.summary %></td>
        <td><%= work_order.est_completion %></td>
        <td><%= work_order.percent_complete %></td>
        <td><%=l work_order.created_at, format: :long %></td>
        <td>
          <%= link_to work_order_path(work_order), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to work_order_path(work_order), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_work_order_path,
            :class => 'btn btn-primary' %>

app/views/work_orders/new.html.erb
<%- model_class = WorkOrder -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => WorkOrder %></h1>
</div>
<%= render :partial => 'form' %>

app/views/work_orders/show.html.erb
<%- model_class = WorkOrder -%>
<div class="page-header">
  <h1><%=t '.title', :default => WorkOrder %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:wo_number) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.wo_number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:start_date) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.start_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:comp_date) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.comp_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:requestor) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.requestor %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:priority) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.priority %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:repair_facility) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.repair_facility %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:repair_type) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.repair_type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:location) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.location %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:summary) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.summary %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:est_completion) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.est_completion %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:percent_complete) %></dt>
      <dd><pre class="prettyprint"><%= @work_order.percent_complete %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              work_orders_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_work_order_path(@work_order), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              work_order_path(@work_order),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>